version: '2'

networks:
  custom:
    name: alluxio-secure-hadoop_custom
    external: true

services:
  kdc-realm2:
    networks:
      custom:
        ipv4_address: 172.23.0.2
    image: sequenceiq/kerberos
    hostname: kdc
    domainname: ${DOMAIN}
    container_name: kdc-realm2
    environment:
      REALM: ${REALM}
      DOMAIN_REALM: ${DOMAIN_REALM}
    volumes:
      - "./config_files/kdc/krb5.conf:/etc/krb5.conf"
      - "/dev/urandom:/dev/random"
      - "/etc/localtime:/etc/localtime:ro"
      - "keytabs:/etc/security/keytabs"
      - "kdc_storage:/var/kerberos/krb5kdc"

  mysql-realm2:
    networks:
      custom:
        ipv4_address: 172.23.0.3
    image: mysql:5.7
    restart: always
    hostname: mysql
    domainname: ${DOMAIN}
    container_name: mysql-realm2
    environment:
      MYSQL_ROOT_PASSWORD: changeme123
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - mysql_data:/var/lib/mysql

  hadoop-namenode-realm2:
    networks:
      custom:
        ipv4_address: 172.23.0.4
    image: myalluxio/alluxio-secure-hadoop:hadoop-2.10.1
    depends_on: 
      - kdc-realm2
      - mysql-realm2
    hostname: hadoop-namenode
    domainname: ${DOMAIN}
    container_name: hadoop-namenode-realm2
    tty: true
    extra_hosts:
      - "kdc.${DOMAIN} kdc:172.23.0.2"
      - "mysql.${DOMAIN} mysql:172.23.0.3"
      - "hadoop-datanode1.${DOMAIN} hadoop-datanode1: 172.23.0.5"
      - "alluxio-master.${DOMAIN} alluxio-master: 172.23.0.6"
      - "alluxio-worker1.${DOMAIN} alluxio-worker1: 172.23.0.7"
    environment:
      KRB_REALM: ${REALM}
      DOMAIN_REALM: ${DOMAIN_REALM}
      THIS_FQDN: hadoop-namenode.${DOMAIN}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN}
      HADOOP_DATANODE1_FQDN: hadoop-datanode1.${DOMAIN}
      ALLUXIO_MASTER_FQDN: alluxio-master.${DOMAIN}
    volumes:
      - ./config_files:/tmp/config_files
      - /etc/localtime:/etc/localtime:ro
      - ./bootstrap/bootstrap-hadoop-namenode.sh:/bootstrap.sh
      - hdfs_storage:/opt/hadoop/data
      - keytabs:/etc/security/keytabs
      - keystore:/etc/ssl/certs
    expose:
     - 8020
     - 9000
     - 10020
     - 8030
     - 8031
     - 8032
     - 8033
     - 8040
     - 8042
     - 8088
     - 7077
     - 9083
    ports:
      - "51470:50470"
      - "18888:19888"
      - "11002:10002"
      - "8188:8088"
      - "8180:8080"
    command: ["/bootstrap.sh"]

  hadoop-datanode1-realm2:
    networks:
      custom:
        ipv4_address: 172.23.0.5
    image: myalluxio/alluxio-secure-hadoop:hadoop-2.10.1
    depends_on: 
      - kdc-realm2
      - mysql-realm2
      - hadoop-namenode-realm2
    hostname: hadoop-datanode1
    domainname: ${DOMAIN}
    container_name: hadoop-datanode1-realm2
    tty: true
    extra_hosts:
      - "kdc.${DOMAIN} kdc:172.23.0.2"
      - "mysql.${DOMAIN} mysql:172.23.0.3"
      - "hadoop-namenode.${DOMAIN} hadoop-namenode: 172.23.0.4"
      - "alluxio-master.${DOMAIN} alluxio-master: 172.23.0.6"
      - "alluxio-worker1.${DOMAIN} alluxio-worker1: 172.23.0.7"
    environment:
      KRB_REALM: ${REALM}
      DOMAIN_REALM: ${DOMAIN_REALM}
      THIS_FQDN: hadoop-datanode1.${DOMAIN}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN}
      HADOOP_DATANODE1_FQDN: hadoop-datanode1.${DOMAIN}
      ALLUXIO_MASTER_FQDN: alluxio-master.${DOMAIN}
    volumes:
      - ./config_files:/tmp/config_files
      - /etc/localtime:/etc/localtime:ro
      - ./bootstrap/bootstrap-hadoop-datanode.sh:/bootstrap.sh
      - hdfs_storage:/opt/hadoop/data
      - keytabs:/etc/security/keytabs
      - keystore:/etc/ssl/certs
    expose:
     - 50010
     - 50020
     - 50075
    ports:
      - "51076:50075"
      - "8281:8081"
      - "8144:8044"
    command: ["/bootstrap.sh"]

  alluxio-master-realm2:
    image: myalluxio/alluxio-secure-hadoop:hadoop-2.10.1
    networks:
      custom:
        ipv4_address: 172.23.0.6
    depends_on:
      - kdc-realm2
    hostname: alluxio-master
    domainname: ${DOMAIN}
    container_name: alluxio-master-realm2
    tty: true
    extra_hosts:
      - "kdc.${DOMAIN} kdc: 172.23.0.2"
      - "hadoop-namenode.${DOMAIN} hadoop-namenode: 172.23.0.4"
      - "hadoop-datanode1.${DOMAIN} hadoop-datanode1: 172.23.0.5"
      - "alluxio-master.${DOMAIN} alluxio-master: 172.23.0.6"
      - "alluxio-worker1.${DOMAIN} alluxio-worker1: 172.23.0.7"
      - "ranger-admin.${DOMAIN} ranger-admin: 172.23.0.16"
      - "kdc.kerberos.com 172.22.0.2"
      # - "hadoop-namenode.${SRV_DOMAIN_REALM1} 172.22.0.4"
      # - "hadoop-datanode1.${SRV_DOMAIN_REALM1} 172.22.0.5"
    environment:
      KRB_REALM: ${REALM}
      DOMAIN_REALM: ${DOMAIN_REALM}
      THIS_FQDN: alluxio-master.${DOMAIN}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN}
      HADOOP_NAMENODE_URL: hadoop-namenode.${DOMAIN}:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files:/tmp/config_files
      - ./bootstrap/bootstrap-alluxio-master.sh:/bootstrap.sh
      - keytabs:/etc/security/keytabs
      - keystore:/etc/ssl/certs
    expose:
      - "19998"
      - "19999"
      - "20001"
      - "20002"
      - "19200"
      - "20003"
    ports:
      - "18998:19998"
      - "18999:19999"
      - "4140:4040"
    command: ["/bootstrap.sh"]

  alluxio-worker1-realm2:
    image: myalluxio/alluxio-secure-hadoop:hadoop-2.10.1
    networks:
      custom:
        ipv4_address: 172.23.0.7
    shm_size: '1gb'
    depends_on:
      - kdc-realm2
      - alluxio-master-realm2
    hostname: alluxio-worker1
    domainname: ${DOMAIN}
    container_name: alluxio-worker1-realm2
    tty: true
    extra_hosts:
      - "kdc.${DOMAIN} kdc: 172.23.0.2"
      - "hadoop-namenode.${DOMAIN} hadoop-namenode: 172.23.0.4"
      - "hadoop-datanode1.${DOMAIN} hadoop-datanode1: 172.23.0.5"
      - "alluxio-master.${DOMAIN} alluxio-master: 172.23.0.6"
      - "ranger-admin.${DOMAIN} ranger-admin: 172.23.0.16"
    environment:
      KRB_REALM: ${REALM}
      DOMAIN_REALM: ${DOMAIN_REALM}
      THIS_FQDN: alluxio-worker1.${DOMAIN}
      ALLUXIO_MASTER_FQDN: alluxio-master.${DOMAIN}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN}
      HADOOP_NAMENODE_URL: hadoop-namenode.${DOMAIN}:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files:/tmp/config_files
      - ./bootstrap/bootstrap-alluxio-worker.sh:/bootstrap.sh
      - keytabs:/etc/security/keytabs
      - keystore:/etc/ssl/certs
    expose:
      - "29999"
      - "30000"
      - "30001"
      - "30003"
      - "39999"
    ports:
      - "31000:30000"
      - "31003:30003"
      - "38999:39999"
    command: ["/bootstrap.sh"]

  presto-server-realm2:
    networks:
      custom:
        ipv4_address: 172.23.0.14
    image: myalluxio/presto:0.276
    container_name: presto-server-realm2
    hostname: presto-server
    domainname: docker.com
    extra_hosts:
      - "kdc.kerberos.com kdc: 172.23.0.2"
      - "hadoop-namenode.docker.com hadoop-namenode: 172.23.0.4"
      - "hadoop-datanode1.docker.com hadoop-datanode1: 172.23.0.5"
      - "alluxio-master.docker.com alluxio-master: 172.23.0.6"
      - "alluxio-worker1.docker.com alluxio-worker1: 172.23.0.7"
    expose:
      - 8080
    ports:
      - 8282:8080 # publish presto http port 8080 for web as 8181
    volumes:
      - "./bootstrap/bootstrap-presto.sh:/bootstrap.sh"
      - "./config_files/presto:/opt/presto-server/etc"
      - "./config_files/kdc/krb5.conf:/etc/krb5.conf"
      - "keytabs:/etc/security/keytabs"
    entrypoint: ["/bootstrap.sh"]

  # TODO: use single mysql container for multiple databases
  db-realm2:
    image: mysql:5.7
    container_name: ranger-db-realm2
    hostname: db
    domainname: docker.com
    networks:
      custom:
        ipv4_address: 172.23.0.15
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ranger
      MYSQL_USER: ranger
      MYSQL_PASSWORD: ranger
    expose:
      - "3306"

  ranger-admin-realm2:
    image: kadensungbincho/ranger-admin:2.1.0
    container_name: ranger-admin-realm2
    hostname: ranger
    domainname: docker.com
    networks:
      custom:
        ipv4_address: 172.23.0.16
    extra_hosts:
      - "kdc.kerberos.com kdc:172.23.0.2"
    environment:
      JAVA_OPTS: -Djavax.net.ssl.trustStore=/etc/ssl/certs/ranger/ranger-admin-truststore.jks -Djavax.net.ssl.trustStorePassword=changeme123
    depends_on:
      - kdc-realm2
      - db-realm2
    tty: true
    volumes:
      - ./bootstrap/bootstrap-ranger-admin.sh:/opt/ranger_admin/bootstrap.sh
      - ./config_files/ranger/admin/install.properties:/opt/ranger_admin/install.properties
      - ./config_files/ranger/admin/ranger-admin-site.xml:/opt/ranger_admin/ews/webapp/WEB-INF/classes/conf/ranger-admin-site.xml
      - ./config_files/ranger/admin/ranger-admin-default-site.xml:/opt/ranger_admin/ews/webapp/WEB-INF/classes/conf/ranger-admin-default-site.xml
      - ./config_files/ranger/admin/security-applicationContext.xml:/opt/ranger_admin/ews/webapp/WEB-INF/classes/conf/security-applicationContext.xml
      - ./config_files/ranger/admin/core-site.xml:/opt/ranger_admin/conf/core-site.xml
      - ./config_files/kdc/krb5.conf:/etc/krb5.conf
      - keystore:/etc/ssl/certs
      - keytabs:/etc/security/keytabs
    command: ["./bootstrap.sh"]
    ports:
      - "6183:6182"
    restart: always

volumes:
  kdc_storage:
    driver: local
  keytabs:
    driver: local
  keystore:
    driver: local
  hdfs_storage:
    driver: local
  mysql_data:
    driver: local
  prometheus_data:
    driver: local
  db_data:
    driver: local
