version: '3.11'

services:
  kdc:
    hostname: kdc.${DOMAIN_1}
    container_name: kdc-${DOMAIN_1}
    environment:
      REALM: ${REALM_1}
      DOMAIN_REALM: kdc.${DOMAIN_1}

  mysql:
    hostname: mysql.${DOMAIN_1}
    container_name: mysql-${DOMAIN_1}

  hadoop-namenode:
    hostname: hadoop-namenode.${DOMAIN_1}
    container_name: hadoop-namenode-${DOMAIN_1}
    depends_on: 
      - kdc-${DOMAIN_1}
      - mysql-${DOMAIN_1}
    environment:
      KRB_REALM: ${REALM_1}
      DOMAIN_REALM: kdc.${DOMAIN_1}
      THIS_FQDN: hadoop-namenode.${DOMAIN_1}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN_1}
      HADOOP_DATANODE1_FQDN: hadoop-datanode1.${DOMAIN_1}
      ALLUXIO_MASTER_FQDN: alluxio-master.${DOMAIN_1}
      MYSQL_FQDN: mysql.${DOMAIN_1}
    ports:
      - "51470:50470"
      - "11888:19888"
      - "11002:10002"
      - "8188:8088"
      - "8180:8080"