version: '3.11'

services:
  kdc:
    hostname: kdc.${DOMAIN_2}
    environment:
      REALM: ${REALM_2}
      DOMAIN_REALM: kdc.${DOMAIN_2}

  mysql:
    hostname: mysql.${DOMAIN_2}

  hadoop-namenode:
    hostname: hadoop-namenode.${DOMAIN_2}
    container_name: hadoop-namenode-${DOMAIN_2}
    depends_on: 
      - kdc-${DOMAIN_2}
      - mysql-${DOMAIN_2}
    environment:
      KRB_REALM: ${REALM_2}
      DOMAIN_REALM: kdc.${DOMAIN_2}
      THIS_FQDN: hadoop-namenode.${DOMAIN_2}
      HADOOP_NAMENODE_FQDN: hadoop-namenode.${DOMAIN_2}
      HADOOP_DATANODE1_FQDN: hadoop-datanode1.${DOMAIN_2}
      ALLUXIO_MASTER_FQDN: alluxio-master.${DOMAIN_2}
      MYSQL_FQDN: mysql.${DOMAIN_1}
    ports:
      - "52470:50470"
      - "12888:19888"
      - "12002:10002"
      - "8288:8088"
      - "8280:8080"